/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package topology;

import java.io.FileNotFoundException;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        proc processTable = new proc();
        try {
            System.out.println(processTable.getDefaultRoute());
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
    }
}
